# Generated by Django 2.1.5 on 2019-02-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20180417_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='username',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
